name: BRMesh Bridge
version: "0.12.0"
slug: brmesh-bridge
description: Advanced BRMesh light management with map view, effects, and multi-controller support
url: https://github.com/tofuweasel/ha-brmesh-bridge
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
uart: true
usb: true
bluetooth: true
hassio_api: true
homeassistant_api: true
services:
  - mqtt:need
host_network: true
ingress: true
ingress_port: 8099
panel_icon: mdi:lightbulb-group
webui: http://[HOST]:[PORT:8099]
options: {}
schema: {}
