name: ESP BLE Bridge
version: 0.50.7

slug: esp-ble-bridge
description: ESP32 BLE bridge for Fastcon/BRMesh lights with native mesh-based pairing, automatic device detection, and complete protocol support
url: https://github.com/tofuweasel/ha-esp-ble-bridge
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
uart: true
usb: true
bluetooth: true
hassio_api: true
homeassistant_api: true
services:
  - mqtt:need
host_network: true
map:
  - config:rw
ingress: true
ingress_port: 8099
panel_icon: mdi:lightbulb-group
webui: http://[HOST]:[PORT:8099]
options: {}
schema: {}
